version: "3.3"

services:
  express:
    build:
      context: ./expressjs/
      dockerfile: Dockerfile

  fastapi:
    build:
      context: ./fastapi/
      dockerfile: Dockerfile

  gin:
    build:
      context: ./go/
      dockerfile: Dockerfile

  luminous:
    build:
      context: ./luminous-clj/
      dockerfile: Dockerfile
    environment:
      "database-url": "jdbc:h2:./luminous_clj_dev.db"

  helidon-se:
    build:
      context: ./helidon-se/
      dockerfile: Dockerfile

  micronaut:
    build:
      context: ./micronaut/
      dockerfile: Dockerfile

  quarkus:
    build:
      context: ./quarkus/
      dockerfile: src/main/docker/Dockerfile.jvm