micronaut:
  server:
    port: 3006
  application:
    name: micronaut
    instance:
      id: ${random.shortuuid}
consul:
  client:
    connect-ttl: 30s
    registration:
      enabled: true
      check:
        http: true
    defaultZone:
      - "172.22.0.21:8500"
      - "172.22.0.22:8500"
      - "172.22.0.23:8500"